"""add room table

Revision ID: 5605bbfaf72a
Revises: 569bd755dc5a
Create Date: 2026-07-07 16:18:09.732384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5605bbfaf72a'
down_revision = '569bd755dc5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostel_id', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.String(length=50), nullable=False),
    sa.Column('sharing_type', sa.String(length=30), nullable=False),
    sa.Column('monthly_fee', sa.Float(), nullable=False),
    sa.Column('total_beds', sa.Integer(), nullable=False),
    sa.Column('available_beds', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('facilities', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hostel_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rooms')
    # ### end Alembic commands ###
