"""Hostel fields updated

Revision ID: 569bd755dc5a
Revises: 4b54579bd1fd
Create Date: 2026-07-07 00:10:03.392735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '569bd755dc5a'
down_revision = '4b54579bd1fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hostel_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('monthly_fee', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('total_capacity', sa.Integer(), nullable=False))
        batch_op.drop_column('max_guests')
        batch_op.drop_column('property_type')
        batch_op.drop_column('price_per_night')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_per_night', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('property_type', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('max_guests', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('total_capacity')
        batch_op.drop_column('monthly_fee')
        batch_op.drop_column('hostel_type')

    # ### end Alembic commands ###
