"""add student table

Revision ID: d9bb34dcbc1d
Revises: 5605bbfaf72a
Create Date: 2026-07-07 17:07:09.002786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9bb34dcbc1d'
down_revision = '5605bbfaf72a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('aadhaar_number', sa.String(length=20), nullable=True),
    sa.Column('college_name', sa.String(length=200), nullable=False),
    sa.Column('course', sa.String(length=100), nullable=False),
    sa.Column('semester', sa.String(length=30), nullable=False),
    sa.Column('guardian_name', sa.String(length=150), nullable=False),
    sa.Column('guardian_phone', sa.String(length=15), nullable=False),
    sa.Column('emergency_contact', sa.String(length=15), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=20), nullable=False),
    sa.Column('profile_photo', sa.String(length=255), nullable=True),
    sa.Column('id_proof', sa.String(length=255), nullable=True),
    sa.Column('admission_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aadhaar_number'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    # ### end Alembic commands ###
