"""add hostel_id to notice

Revision ID: e1a2b3c4d5f6
Revises: 04ffbbf0332a
Create Date: 2026-07-18 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a2b3c4d5f6'
down_revision = '04ffbbf0332a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'notices',
        sa.Column('hostel_id', sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        'fk_notices_hostel_id_properties',
        'notices',
        'properties',
        ['hostel_id'],
        ['id']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_notices_hostel_id_properties',
        'notices',
        type_='foreignkey'
    )
    op.drop_column('notices', 'hostel_id')
    # ### end Alembic commands ###
