"""add settings fields to admin

Revision ID: f2b3c4d5e6a7
Revises: e1a2b3c4d5f6
Create Date: 2026-07-22 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2b3c4d5e6a7'
down_revision = 'e1a2b3c4d5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('admins', sa.Column('avatar_url', sa.String(length=255), nullable=True))
    op.add_column(
        'admins',
        sa.Column('theme_accent', sa.String(length=20), nullable=False, server_default='blue')
    )
    op.add_column(
        'admins',
        sa.Column('theme_mode', sa.String(length=10), nullable=False, server_default='light')
    )
    op.add_column('admins', sa.Column('notification_prefs', sa.Text(), nullable=True))
    op.add_column(
        'admins',
        sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'updated_at')
    op.drop_column('admins', 'notification_prefs')
    op.drop_column('admins', 'theme_mode')
    op.drop_column('admins', 'theme_accent')
    op.drop_column('admins', 'avatar_url')
    op.drop_column('admins', 'phone')
    # ### end Alembic commands ###
